id: P008273
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4642
  title: ཡང་དག་ལམ་གྱི་འཇུག་སྒོ་བློ་གསར་ཡིད་ཀྱི་དགའ་སྟོན། ༼དེབ་བཞི་པ།༽
  author: ''
  volumes:
    854fd1ae5f434d37bb79d2b4081a4b5d:
      image_group_id: I3CN4644
      title: ''
      volume_number: 1
      total_pages: 416
      base_file: v001.txt
